blueprint:
  name: BTHome Temperature Sensor Update Time Tracker
  description: >
    Tracks the last time the temperature changes, to allow for staleness monitoring. V3

  domain: automation
  input:
    temp_sensor:
      name: Temperature Sensor To Track
      description: >
        The BTHome Temperature Sensor that you wish to monitor last update time of.
      selector:
        entity:
          filter:
            - integration: bthome
            - device_class: temperature
    date_input:
      name: Date/Time Input To Sync
      description: >
        An input_datetime entity to record last time of temperature change.

      selector:
        entity:
          domain: input_datetime

triggers:
 - trigger: state
   entity_id: !input temp_sensor

actions:
  - action: input_datetime.set_datetime
    target:
      entity_id: !input date_input
    data:
      timestamp: "{{ now().timestamp() }}"

mode: single
max_exceeded: silent
