# Modified from https://github.com/ClaymoreTech4/HABlueprints-Team-Tracker/blob/main/teamtrackerblueprint.yaml
blueprint:
  name: Team Event Management
  description: >
    Manages team score updates, and game state events. Allows adding additional actions after key events. V9

  domain: automation
  input:
    team_sensor:
      name: Team Sensor
      description: >
        The sensor entity tracking the team's state and score (e.g., sensor.mariners_baseball).

      selector:
        entity:
          integration: teamtracker
          multiple: false
    event_input_text:
      name: Event Type input_text
      description: >
        An input_text entity for displaying the game event type (e.g., Touchdown, Extra Point). This can be used for dashboards and conditionals, for example.

      selector:
        entity:
          domain: input_text
    team_score_counter:
      name: Team Score Counter
      description: >
        A counter entity, which will statefully store the team's score during the game.

      selector:
        entity:
          domain: counter
    update_teamtracker_sensor:
      name: Sensor Update Rate
      description: This sets how often the Team Tracker Sensor should update, when the game is playing (State = "IN") Every 10 to 59 seconds
      default: 30
      selector:
        number:
          min: 10
          max: 59
          mode: box
    game_start_actions:
      name: Game Starts Actions
      description: >
        A sequence of actions to perform after game starts.

      default: []
      selector:
        action: {}
    game_end_actions:
      name: Game Ends Actions
      description: >
        A sequence of actions to perform after game ends.

      default: []
      selector:
        action: {}
    team_scored_actions:
      name: Team Score Actions
      description: >
        A sequence of actions to perform after the team scores.

      default: []
      selector:
        action: {}
    team_score_overturned_actions:
      name: Team Score Overturned Actions
      description: >
        A sequence of actions to perform after the team score is reduced.

      default: []
      selector:
        action: {}
variables:
  game_state: !input team_sensor
  us_score_prev: !input team_score_counter
triggers:
  - trigger: state
    entity_id: !input team_sensor
action:
  # Do all the steps of a single invocation.
  - parallel:
      # During games, hammer the F5 key.
      - if:
          - condition: state
            entity_id: !input team_sensor
            state: "IN"
        then:
          - sequence:
              - delay: !input update_teamtracker_sensor
              - action: homeassistant.reload_config_entry
                target:
                  entity_id: !input team_sensor
                data: {}
      - choose:
          # Game Starting
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state == "IN" and trigger.from_state.state == "PRE" }}

            sequence:
              - parallel:
                  - sequence:
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: Game Starting
                      - delay: "00:00:30"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: None
                  - sequence: !input game_start_actions
          # Team Scored
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state == "IN" and ( state_attr(game_state, 'team_score') | int(0) > states(us_score_prev) | int(0) ) }}
            sequence:
              - parallel:
                  - sequence:
                      - action: counter.set_value
                        target:
                          entity_id: !input team_score_counter
                        data:
                          value: "{{state_attr(game_state, 'team_score') | int}}"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: Team Scored
                      - delay: "00:00:30"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: None
                  - sequence: !input team_scored_actions
          # Team Score Clawed Back
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state == "IN" and ( state_attr(game_state, 'team_score') | int(0) < states(us_score_prev) | int(0) ) }}
            sequence:
              - parallel:
                  - sequence:
                      - action: counter.set_value
                        target:
                          entity_id: !input team_score_counter
                        data:
                          value: "{{state_attr(game_state, 'team_score') | int}}"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: Team Score Overturned
                      - delay: "00:00:30"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: None
                  - sequence: !input team_score_overturned_actions
          # Game Ending
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state == "POST" and trigger.from_state.state == "IN" }}

            sequence:
              - parallel:
                  - sequence:
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: Game Ending
                      - delay: "00:00:30"
                      - service: input_text.set_value
                        target:
                          entity_id: !input event_input_text
                        data:
                          value: None
                  - sequence: !input game_end_actions
mode: parallel
